# Generated by Django 4.1.5 on 2023-01-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('pulsometer', models.FloatField()),
                ('efficiency', models.FloatField()),
                ('red_value', models.IntegerField()),
                ('green_value', models.IntegerField()),
                ('blue_value', models.IntegerField()),
            ],
        ),
    ]
